### ISSUE TITLE
Still multiple Values

### ISSUE THREAD

**Issue by Caliban2017** [Zwer2k/WeatherStationDataRx#16]
Hello, i posted an Issue some Months ago here about multiple Values. There are all Measuments Three times in the Serial Monitor. I used your new version of the Sketch, everything is working again so far, but the Values are still the same as before, every Measument is shown three times in the Serial Monitor. So the Issue is still there...

Greetings

**Comment by Zwer2k** [comment]
Hello,
have you set appropriate parameters in the constructor?

The third parameter must be true.
WeatherStationDataRx wsdr(DATA_PIN, true, true, false);

This parameter causes the data to be made available with a slight delay. Originally it was 1 second, but now I have increased it to 3 seconds because duplicate messages were still being output from time to time.

Many greetings
